// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6pgiQ9jmAQXobT_DsmFjtwl1vXLpxy5Y',
    appId: '1:956955331530:web:28012e95862dc18773dd33',
    messagingSenderId: '956955331530',
    projectId: 'mychat-3aacc',
    authDomain: 'mychat-3aacc.firebaseapp.com',
    storageBucket: 'mychat-3aacc.appspot.com',
    measurementId: 'G-5VRVCEJGYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo5K0CveXjkZ_BSfzhX7jQeExHWDV23C0',
    appId: '1:956955331530:android:c31f9c6b3c857bdf73dd33',
    messagingSenderId: '956955331530',
    projectId: 'mychat-3aacc',
    storageBucket: 'mychat-3aacc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCP0iYOhOu82ePPIstxlqP_rpT4jwq8Iw',
    appId: '1:956955331530:ios:9919c8a11c149a4773dd33',
    messagingSenderId: '956955331530',
    projectId: 'mychat-3aacc',
    storageBucket: 'mychat-3aacc.appspot.com',
    androidClientId: '956955331530-9j5rpssjfqih85gbnvtpejs8ksbptscv.apps.googleusercontent.com',
    iosClientId: '956955331530-1eoupkiai3580h8e2nbfletorunlmup6.apps.googleusercontent.com',
    iosBundleId: 'com.persona.mychat',
  );
}
